var ninon = {
	name: "Ninon",
	currentHp: 7116,
	currentEnergy: 0,
	hp: 7116,
	atk: 1456,
	magic_str: 0,
	def: 83,
	magic_def: 49,
	physical_critical: 20,
	magic_critical: 0,
	wave_hp_recovery: 270,
	wave_energy_recovery: 5,
	dodge: 3,
	physical_penetrate: 0,
	magic_penetrate: 0,
	life_steal: 0,
	hp_recovery_rate:0,
	energy_recovery_rate: 0,
	energy_reduce_rate: 0,
	accuracy: 0,
	atk_type: 1,
	union_burst_level: 48,
	main_skill_1_level: 48,
	main_skill_2_level: 48,
	ex_skill_1_level: 0,
	level: 48, 
	rarity: 3,
	bond: 8,
	unique_equipment_unlocked: false,
	atk_type: 1,
	motion_type: 0,
	se_type: 0,
	move_speed: 450,
	search_area_width: 400,
	normal_atk_cast_time: 2
}
// should be 4258.1 power

var hatsune = {
	name: "Hatsune",
	currentHp: 5247,
	currentEnergy: 0,
	hp: 5247,
	atk: 0,
	magic_str: 1613,
	def: 42,
	magic_def: 73,
	physical_critical: 0,
	magic_critical: 0,
	wave_hp_recovery: 100,
	wave_energy_recovery: 85,
	dodge: 0,
	physical_penetrate: 0,
	magic_penetrate: 0,
	life_steal: 0,
	hp_recovery_rate: 15,
	energy_recovery_rate: 0,
	energy_reduce_rate: 0,
	accuracy: 0,
	atk_type: 1,
	union_burst_level: 48,
	main_skill_1_level: 48,
	main_skill_2_level: 48,
	ex_skill_1_level: 0,
	level: 48, 
	rarity: 3,
	bond: 7,
	unique_equipment_unlocked: false,
	atk_type: 2
}
// should be 4145.7 power